# Generated by Django 3.0.1 on 2022-05-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20220501_0101'),
        ('spotify', '0003_auto_20220501_0956'),
    ]

    operations = [
    ]
