# Generated by Django 3.2.13 on 2022-05-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_spotifytoken_id'),
        ('spotify', '0004_merge_20220501_0155'),
    ]

    operations = [
    ]
