# Generated by Django 3.0.1 on 2022-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_spotifytoken_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
