# Generated by Django 3.0.1 on 2022-05-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_auto_20220501_2237'),
        ('spotify', '0008_auto_20220501_1332'),
    ]

    operations = [
    ]
