# Generated by Django 3.0.1 on 2022-05-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20220501_1332'),
        ('study', '0004_auto_20220501_2237'),
    ]

    operations = [
    ]
