# Generated by Django 3.2.13 on 2022-05-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220501_0140'),
        ('accounts', '0009_merge_20220501_0155'),
    ]

    operations = [
    ]
