# Generated by Django 3.0.1 on 2022-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220501_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='useremail',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertimezone',
            field=models.CharField(choices=[('gmt', 'GMT'), ('utc', 'UTC'), ('ect', 'ECT'), ('eet', 'EET'), ('met', 'MET'), ('ctt', 'CTT'), ('jst', 'JST'), ('act', 'ACT'), ('pst', 'PST'), ('cst', 'CST'), ('est', 'EST')], max_length=10),
        ),
    ]
