# Generated by Django 3.0.1 on 2022-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220501_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='useremail',
            field=models.EmailField(max_length=128),
        ),
    ]
