# Generated by Django 3.0.1 on 2022-05-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220501_1332'),
        ('accounts', '0014_auto_20220501_2240'),
    ]

    operations = [
    ]
