# Generated by Django 3.0.1 on 2022-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20220501_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertimezone',
            field=models.CharField(choices=[('1', 'GMT'), ('2', 'UTC'), ('3', 'ECT'), ('4', 'EET'), ('5', 'MET'), ('6', 'CTT'), ('7', 'JST'), ('8', 'ACT'), ('9', 'PST'), ('10', 'CST'), ('11', 'EST')], max_length=10),
        ),
    ]
