# Generated by Django 3.2.13 on 2022-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20220501_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertimezone',
            field=models.CharField(choices=[('1', 'GMT'), ('2', 'UTC'), ('3', 'ECT'), ('4', 'EET'), ('5', 'MET'), ('6', 'CTT'), ('7', 'JST'), ('8', 'ACT'), ('9', 'PST'), ('10', 'CST'), ('11', 'EST')], max_length=10),
        ),
    ]
