# Generated by Django 3.0.1 on 2022-05-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220501_1524'),
        ('accounts', '0016_auto_20220501_1426'),
    ]

    operations = [
    ]
